### ISSUE TITLE
make attestations & encoding-hosting-challenge flows work

### ISSUE THREAD

**Issue by serapath** [playproject-io/datdot-substrate#20]
## `@todo`
* [x] finish attestation
* [ ] adding logic for register as encoder, attester etc.
* [ ] add new related substrate events etc. to hackMD with rust API
* [ ] figure out and document merkle proof format

---
